import { describe, it, expect } from 'vitest';
import {
  SEED_PIECES,
  SEED_PEOPLE,
  splitParticipants,
  livingRoster,
  roleOf,
  hiddenReplies,
  chaseTicks,
  brokenTakes,
  foldFaces,
  composeEventLog,
  WEEKDAYS,
  normalizePiece,
  localSlot,
  whenMarks,
  areaRadius,
  aggregate,
  longestPiece,
  fmtDuration,
  fmtSeconds,
  fmtStopwatch,
  fmtElapsed,
  pieceSlug,
  piecePath,
  findPieceByRef,
  isRatioedParent,
} from './ratioed.js';

// The seed is regenerated by the build now (see writeRatioedSeed), so these
// assert its SHAPE and its internal agreement rather than a count that changes
// every time a piece is sealed. A test that had to be edited after every piece
// is a test nobody keeps honest.
// The pieces the bundled roster actually covers. The seed is regenerated by
// the build and now spans every take; SEED_PEOPLE is a frozen harvest of the
// first eleven. Pairing all of one with all of the other tests a mismatch
// nothing in the app creates — every real caller passes the roster the build
// wrote, which knows about both.
const BUNDLED_TAKES = new Set(SEED_PEOPLE.flatMap((p) => [...p.pre, ...p.post]));
const SEEDED_PIECES = SEED_PIECES.filter((p) => BUNDLED_TAKES.has(p.take));

describe('SEED_PIECES', () => {
  it('carries every sealed piece, in take order, with no gaps', () => {
    expect(SEED_PIECES.length).toBeGreaterThanOrEqual(11);
    const takes = SEED_PIECES.map((p) => p.take);
    expect(takes).toEqual([...takes].sort((a, b) => a - b));
    expect(new Set(takes).size).toBe(takes.length);
    expect(takes[0]).toBe(1);
    expect(takes[takes.length - 1]).toBe(takes.length);
  });

  it('keys each record by its subject post rkey', () => {
    for (const p of SEED_PIECES) {
      expect(p.subject.endsWith(`/${p.rkey}`)).toBe(true);
    }
  });

  it('seals every piece after it was posted', () => {
    for (const p of SEED_PIECES) {
      const span = Date.parse(p.sealedAt) - Date.parse(p.postedAt);
      expect(span).toBeGreaterThan(0);
      // lifespanMs is derived from those two timestamps, so it must agree with
      // them to the millisecond.
      expect(Math.abs(span - p.lifespanMs)).toBeLessThanOrEqual(1);
    }
  });

  it('records a reaction time whenever the like survived', () => {
    for (const p of SEED_PIECES) {
      // The converse no longer holds, and that is the point of
      // `reactionRecovered`: a like the studio watched land and somebody then
      // deleted is timed by the log, not by any index.
      if (p.breaker.likeSurvives) expect(typeof p.breaker.reactionMs).toBe('number');
      if (typeof p.breaker.reactionMs === 'number' && !p.breaker.likeSurvives) {
        expect(p.breaker.reactionRecovered).toBe(true);
      }
    }
  });

  it('measures a reaction in seconds, not minutes', () => {
    const measured = SEED_PIECES.map((p) => p.breaker.reactionMs).filter(
      (ms) => typeof ms === 'number',
    );
    expect(measured.length).toBeGreaterThanOrEqual(5);
    for (const ms of measured) {
      expect(ms).toBeGreaterThan(0);
      expect(ms).toBeLessThan(60_000);
    }
  });

  it('has a breaker on every piece', () => {
    for (const p of SEED_PIECES) {
      expect(typeof p.breaker.likeSurvives).toBe('boolean');
      expect(p.breaker.handle).toBeTruthy();
    }
  });

  it('never claims a like arrived while a piece was alive except from its breaker', () => {
    // Any surviving pre-seal like IS the breaking like, so a piece with a
    // pre-seal like must be one whose breaker's like survived.
    for (const p of SEED_PIECES) {
      if (p.preSeal.likes > 0) expect(p.breaker.likeSurvives).toBe(true);
    }
  });
});

describe('normalizePiece', () => {
  it('fills in missing engagement blocks rather than throwing', () => {
    const p = normalizePiece('abc', { take: 3, subject: 'at://x', lifespanMs: 100 });
    expect(p.preSeal).toEqual({
      likes: 0,
      reposts: 0,
      quotes: 0,
      threadPosts: 0,
      participants: 0,
    });
    expect(p.postSeal.likes).toBe(0);
    expect(p.breaker.handle).toBe('unknown');
  });

  it('returns null for an absent value', () => {
    expect(normalizePiece('abc', null)).toBeNull();
  });

  it('decodes a recorded event log into the seconds the charts plot', () => {
    // Records carry milliseconds — lexicon v1 has no float type — while the
    // harvested log and every chart work in seconds.
    const p = normalizePiece('abc', {
      take: 12,
      events: [
        { k: 'reply', h: 'b.test', offMs: 22723, pre: 1, self: 1 },
        { k: 'like', h: 'a.test', offMs: 892035, pre: 1 },
        { k: 'reply', offMs: 970169, pre: 0, t: 'after the seal' },
      ],
    });
    expect(p.events.map((e) => e.off)).toEqual([22.723, 892.035, 970.169]);
    expect(p.events[0].self).toBe(1);
    expect(p.events[1].self).toBeUndefined();
    expect(p.events[2].h).toBe('(unresolvable)');
    expect(p.events[2].t).toBe('after the seal');
  });

  it('reports no log at all rather than an empty one', () => {
    // The charts fall back to the bundled log on null; an empty array would
    // read as "measured, and nothing happened".
    expect(normalizePiece('abc', { take: 1 }).events).toBeNull();
    expect(normalizePiece('abc', { take: 1, events: [] }).events).toBeNull();
  });

  it('preserves a full record', () => {
    const src = SEED_PIECES[3];
    const p = normalizePiece(src.rkey, src);
    expect(p.take).toBe(4);
    expect(p.preSeal.threadPosts).toBe(src.preSeal.threadPosts);
    expect(p.breaker.likeSurvives).toBe(false);
  });
});

describe('aggregate', () => {
  const stats = aggregate(SEED_PIECES);

  // Figures about the seed, which the build refreshes — so these test the
  // relationships that must hold rather than the values of the day.
  it('measures a reaction for every piece it can, and no more', () => {
    expect(stats.measured).toBeGreaterThanOrEqual(5);
    expect(stats.measured).toBeLessThanOrEqual(stats.count);
    expect(stats.deleted).toBeLessThanOrEqual(stats.count);
  });

  it('puts every reaction in the seconds, and the mean between them', () => {
    expect(stats.minReactionMs).toBeGreaterThan(0);
    expect(stats.meanReactionMs).toBeGreaterThanOrEqual(stats.minReactionMs);
    expect(stats.meanReactionMs).toBeLessThanOrEqual(stats.maxReactionMs);
    expect(stats.maxReactionMs / 1000).toBeLessThan(60);
  });

  it('finds the longest-lived piece', () => {
    const longest = SEED_PIECES.find((p) => p.lifespanMs === stats.maxLifespanMs);
    expect(longest).toBeTruthy();
    for (const p of SEED_PIECES) expect(p.lifespanMs).toBeLessThanOrEqual(stats.maxLifespanMs);
  });

  it('totals the life of every piece in the series', () => {
    const sum = SEED_PIECES.reduce((a, p) => a + p.lifespanMs, 0);
    expect(stats.aliveMs).toBe(sum);
  });

  it('counts far more non-like engagement than likes while alive', () => {
    // The name of the project, as a number: pieces are ratioed by design.
    expect(stats.nonLike).toBeGreaterThan(stats.likes * 10);
  });

  it('handles an empty list without dividing by zero', () => {
    const empty = aggregate([]);
    expect(empty.count).toBe(0);
    expect(empty.meanReactionMs).toBeNull();
    expect(empty.maxLifespanMs).toBe(0);
  });
});

describe('longestPiece', () => {
  it('is the record a live piece is running at', () => {
    const record = longestPiece(SEED_PIECES);
    for (const p of SEED_PIECES) expect(p.lifespanMs).toBeLessThanOrEqual(record.lifespanMs);
  });

  it('never answers with a piece that is still up', () => {
    // A live piece has no lifespan yet. Offering one as the record to beat
    // would have every live piece chasing itself.
    const live = { rkey: 'live', take: 99, postedAt: '2026-08-15T00:00:00Z', lifespanMs: 0 };
    expect(longestPiece([...SEED_PIECES, live]).take).not.toBe(99);
    expect(longestPiece([live])).toBeNull();
  });

  it('is null before anything has ended, which was true exactly once', () => {
    expect(longestPiece([])).toBeNull();
    expect(longestPiece(null)).toBeNull();
  });

  it('keeps the first of a tie, which in take order is the one that got there first', () => {
    const a = { take: 2, sealedAt: 'x', lifespanMs: 1000 };
    const b = { take: 5, sealedAt: 'x', lifespanMs: 1000 };
    expect(longestPiece([a, b]).take).toBe(2);
  });
});

describe('SEED_PEOPLE', () => {
  it('counts everyone by DID, not by handle', () => {
    expect(SEED_PEOPLE).toHaveLength(135);
    expect(new Set(SEED_PEOPLE.map((p) => p.did)).size).toBe(135);
    // Two deactivated accounts share one placeholder handle; counting by
    // handle would silently lose one of them.
    expect(new Set(SEED_PEOPLE.map((p) => p.h)).size).toBe(134);
  });

  it('splits into living and after-the-fact participation', () => {
    const { total, living, afterOnly, breakersListed } = splitParticipants();
    expect(total).toBe(135);
    expect(living).toBe(77);
    expect(living + afterOnly).toBe(total);
    // Seven breakers left any record at all, but one of them — restedwicked,
    // who broke #04 — only shows up after the seal, their like having been
    // deleted. The participants table lists living participation, so it counts
    // six.
    expect(breakersListed).toBe(6);
  });

  it('gives everyone at least one event and one piece', () => {
    for (const p of SEED_PEOPLE) {
      expect(p.ev).toBeGreaterThan(0);
      expect(p.pre.length + p.post.length).toBeGreaterThan(0);
    }
  });

  it('tags only breakers who left a record behind', () => {
    const tagged = SEED_PEOPLE.filter((p) => p.broke);
    // Four of the eleven deleted their like and did nothing else, so they
    // never appear in a backlink index at all.
    expect(tagged).toHaveLength(7);
    for (const p of tagged) {
      expect(p.broke).toBeGreaterThanOrEqual(1);
      expect(p.broke).toBeLessThanOrEqual(11);
    }
  });
});

describe('livingRoster', () => {
  it('lists the measured living participants', () => {
    // 78, not the 77 the roster's own `pre` lists. restedwicked.xyz broke take
    // 4 and deleted the like, so their only surviving record is a reply to the
    // finished post — `pre` is empty and they read as somebody who was never
    // there. Their own roster row is worth more than the stand-in the breaker
    // loop below used to build for them: it carries their display name, their
    // DID, and the afterlife the stand-in knew nothing about.
    const { rows, measured } = livingRoster(SEED_PIECES);
    expect(measured).toBe(78);
    for (const p of rows.slice(0, measured)) expect(p.pre.length).toBeGreaterThan(0);
  });

  it('counts a piece somebody broke as a piece they were there for', () => {
    // The count of pieces is what the participants table ranks by now, and a
    // breaker whose like was deleted has no surviving record of the one act the
    // piece turned on. Reading `pre` alone put them below everyone who replied
    // once to a post that was already over.
    const people = [
      { did: 'did:plc:a', h: 'a.test', ev: 1, pre: [8], post: [], kinds: { reply: 1 }, broke: [7] },
    ];
    const pieces = [{ take: 7, breaker: { handle: 'a.test', likeSurvives: false } }];
    const { rows } = livingRoster(pieces, people);
    expect(rows[0]).toMatchObject({ live: 2, pre: [7, 8], likeGone: true });
  });

  it('recovers the breakers whose like was deleted from the announcement', () => {
    // Their like is gone from every index; the reply concluding the piece is
    // the only record that they were ever there, and leaving them out would
    // drop the people the project is actually about.
    const { rows, named, deleted } = livingRoster(SEEDED_PIECES);
    expect(named).toBe(4);
    // Six pieces lost their breaking like. Four of those breakers left nothing
    // at all and have to be named; j4ck replied to another piece while it was
    // alive and restedwicked replied to their own after the seal, so both were
    // already in the roster — their deleted likes are marked on the rows they
    // already had.
    expect(deleted).toBe(6);
    expect(rows.find((p) => p.h === 'j4ck.xyz')).toMatchObject({ broke: 7, likeGone: true });
    expect(rows.find((p) => p.h === 'restedwicked.xyz')).toMatchObject({
      broke: 4,
      live: 1,
      likeGone: true,
    });
    // `broke` reads through brokenTakes now, since one person can break two.
    const recovered = rows.filter((p) => p.named);
    expect(recovered.flatMap((p) => brokenTakes(p)).sort((a, b) => a - b)).toEqual([2, 5, 8, 10]);
    for (const p of recovered) {
      // No records, one piece. `ev` counts what survives and a deleted like
      // leaves nothing; ending a piece is still being there for it.
      expect(p.ev).toBe(0);
      expect(p.live).toBe(1);
      expect(p.likeGone).toBe(true);
    }
  });

  it('keeps both takes of a breaker who broke two pieces', () => {
    // ponder.ooo broke 15 and 16. The second announcement used to be skipped
    // outright — the person was "already listed" — so the row said one piece
    // and take 16's break was attributed to nobody.
    const pieces = [
      { take: 15, breaker: { handle: 'p.test', likeSurvives: true } },
      { take: 16, breaker: { handle: 'p.test', likeSurvives: true } },
    ];
    const { rows, named } = livingRoster(pieces, []);
    expect(named).toBe(1);
    expect(rows[0]).toMatchObject({ h: 'p.test', live: 2, pre: [15, 16], broke: [15, 16], ev: 2 });
  });

  it('credits a named breaker whose like is still standing', () => {
    // Piece 12 was measured after the roster was built, so its breaker is
    // missing from it — but their like is real and countable, and calling it
    // deleted would be a plain falsehood about a person.
    const pieces = [
      { take: 12, breaker: { handle: 'still.here', likeSurvives: true, reactionMs: 12659 } },
    ];
    const { rows, named, deleted } = livingRoster(pieces, []);
    expect(named).toBe(1);
    expect(deleted).toBe(0);
    expect(rows[0]).toMatchObject({ h: 'still.here', ev: 1, live: 1, likeGone: false });
    expect(rows[0].kinds).toEqual({ like: 1 });
  });

  it('marks a breaker whose like was deleted, wherever their row came from', () => {
    // The mark belongs to the piece, not to how the person got into the list.
    const pieces = [{ take: 1, breaker: { handle: 'a.test', likeSurvives: false } }];
    const people = [{ did: 'did:plc:a', h: 'a.test', ev: 1, pre: [2], post: [], kinds: { reply: 1 }, broke: 1 }];
    const { rows } = livingRoster(pieces, people);
    expect(rows[0]).toMatchObject({ likeGone: true, broke: 1 });
  });

  it('counts every breaker it lists', () => {
    const { rows, breakers } = livingRoster(SEEDED_PIECES);
    expect(breakers).toBe(rows.filter((p) => brokenTakes(p).length).length);
    expect(breakers).toBe(SEEDED_PIECES.length); // one per piece it covers
  });

  it('never lists a breaker twice', () => {
    const { rows } = livingRoster(SEEDED_PIECES);
    expect(new Set(rows.map((p) => p.did)).size).toBe(rows.length);
    // Every piece is accounted for by exactly one row.
    const broke = rows.flatMap((p) => brokenTakes(p));
    expect(new Set(broke).size).toBe(broke.length);
  });

  it('accounts for every piece that names a breaker', () => {
    const { rows } = livingRoster(SEEDED_PIECES);
    const named = new Set(rows.flatMap((p) => brokenTakes(p)));
    for (const piece of SEEDED_PIECES) {
      if (piece.breaker.handle && piece.breaker.handle !== 'unknown') {
        expect(named.has(piece.take)).toBe(true);
      }
    }
  });

  it('matches a breaker to a measured row by handle, not just DID', () => {
    // The announcement records a handle; the roster is keyed by DID. Missing
    // the match would list the same person twice.
    const people = [
      { did: 'did:plc:a', h: 'breaker.test', ev: 2, pre: [1], post: [], kinds: { reply: 2 } },
    ];
    const pieces = [{ take: 1, breaker: { handle: 'breaker.test', likeSurvives: true } }];
    const { rows, named } = livingRoster(pieces, people);
    expect(named).toBe(0);
    expect(rows).toHaveLength(1);
  });

  it('ignores a piece whose breaker was never identified', () => {
    const pieces = [{ take: 1, breaker: { handle: 'unknown' } }, { take: 2, breaker: {} }];
    expect(livingRoster(pieces, []).named).toBe(0);
  });

  it('handles no pieces at all', () => {
    expect(livingRoster(null, []).rows).toEqual([]);
  });

  it('reads the living window off a log that names people by DID', () => {
    // The Mix column and the role both come from `liveKinds`. It used to be
    // looked up by handle alone, and every log written since DIDs were
    // recorded carries the DID — so anyone whose living acts were recorded
    // rather than harvested got nothing, and fell back to counts spanning the
    // afterlife.
    const people = [
      { did: 'did:plc:a', h: 'a.test', ev: 2, pre: [12], post: [12], kinds: { reply: 1, like: 1 } },
    ];
    const events = {
      r12: [
        { k: 'reply', did: 'did:plc:a', h: 'a.test', off: 4, pre: 1 },
        { k: 'like', did: 'did:plc:a', h: 'a.test', off: 900, pre: 0 },
      ],
    };
    const { rows } = livingRoster([{ take: 12, rkey: 'r12', breaker: {} }], people, events);
    expect(rows[0].liveKinds).toEqual({ reply: 1 });
  });

  it('follows a did-less harvest row to the DID another log recorded', () => {
    const people = [
      { did: 'did:plc:a', h: 'a.test', ev: 2, pre: [1, 12], post: [], kinds: { reply: 2 } },
    ];
    const events = {
      r1: [{ k: 'reply', h: 'a.test', off: 4, pre: 1 }],
      r12: [{ k: 'repost', did: 'did:plc:a', h: 'a.test', off: 4, pre: 1 }],
    };
    const { rows } = livingRoster([], people, events);
    expect(rows[0].liveKinds).toEqual({ reply: 1, repost: 1 });
  });

  it('reports an empty living window rather than falling back to the roster', () => {
    // The log covers this person and holds nothing of theirs from before the
    // seal. Falling back to the all-window counts would report their afterlife
    // reply in a column that says it counts the living window.
    const people = [
      { did: 'did:plc:a', h: 'a.test', ev: 1, pre: [], post: [4], kinds: { reply: 1 }, broke: [4] },
    ];
    const events = { r4: [{ k: 'reply', did: 'did:plc:a', h: 'a.test', off: 900, pre: 0 }] };
    const { rows } = livingRoster([{ take: 4, rkey: 'r4', breaker: {} }], people, events);
    expect(rows[0].liveKinds).toEqual({});
  });

  it('credits neither of two accounts sharing one handle', () => {
    // The placeholder for deactivated accounts covers more than one DID.
    const people = [
      { did: 'did:plc:a', h: '(unresolvable)', ev: 1, pre: [1], post: [], kinds: { reply: 1 } },
      { did: 'did:plc:b', h: '(unresolvable)', ev: 1, pre: [1], post: [], kinds: { like: 1 } },
    ];
    const events = { r1: [{ k: 'reply', h: '(unresolvable)', off: 4, pre: 1 }] };
    const { rows } = livingRoster([], people, events);
    for (const row of rows) expect(row.liveKinds).toBe(null);
  });
});

describe('roleOf', () => {
  const person = (kinds, extra = {}) => ({ kinds, ...extra });

  it('names the act that carried the piece furthest, not the commonest one', () => {
    // Nine replies and one repost reads as "reposted": the repost is what took
    // the piece off the thread. The Mix column still shows all ten.
    expect(roleOf(person({ reply: 9, repost: 1 })).label).toBe('reposted');
    expect(roleOf(person({ reply: 3, repost: 2, quote: 1 })).label).toBe('quoted');
    expect(roleOf(person({ reply: 4 })).label).toBe('replied');
  });

  it('lets breaking a piece outrank everything', () => {
    const r = roleOf(person({ reply: 2, quote: 1 }, { broke: 6 }));
    expect(r.label).toBe('broke #06');
    expect(r.key).toBe('broke');
  });

  it('prefers what someone did while the piece was alive', () => {
    // Replied to a living piece, quoted a finished one. Calling them a quoter
    // would credit them with spreading something already over.
    const p = person({ reply: 1, quote: 1 }, { liveKinds: { reply: 1 } });
    expect(roleOf(p).label).toBe('replied');
  });

  it('falls back to the all-window counts when the log says nothing', () => {
    expect(roleOf(person({ repost: 1 }, { liveKinds: null })).label).toBe('reposted');
  });

  it('still names someone whose acts do not fit any of the four', () => {
    expect(roleOf(person({})).label).toBe('was there');
  });

  it('carries a key the palette can colour by', () => {
    expect(roleOf(person({ quote: 1 })).key).toBe('quote');
    expect(roleOf(person({ repost: 1 })).key).toBe('repost');
    expect(roleOf(person({ reply: 1 })).key).toBe('reply');
  });
});

describe('livingRoster living kinds', () => {
  const people = [
    { did: 'did:plc:a', h: 'a.test', ev: 2, pre: [1], post: [2], kinds: { reply: 1, repost: 1 } },
    { did: 'did:plc:x', h: '(unresolvable)', ev: 1, pre: [1], post: [], kinds: { repost: 1 } },
    { did: 'did:plc:y', h: '(unresolvable)', ev: 1, pre: [1], post: [], kinds: { reply: 1 } },
  ];
  const events = {
    r1: [
      { k: 'reply', h: 'a.test', off: 5, pre: 1 },
      { k: 'repost', h: '(unresolvable)', off: 6, pre: 1 },
      { k: 'reply', h: 'dame.is', off: 7, pre: 1, self: 1 },
    ],
    r2: [{ k: 'repost', h: 'a.test', off: 200, pre: 0 }],
  };
  const pieces = [{ take: 1, rkey: 'r1', breaker: { handle: 'a.test' } }];

  it('counts only what landed while a piece was alive', () => {
    const { rows } = livingRoster(pieces, people, events);
    const a = rows.find((p) => p.h === 'a.test');
    // The repost was on a finished piece, so it isn't in the living count.
    expect(a.liveKinds).toEqual({ reply: 1 });
  });

  it('leaves the shared placeholder handle uncredited rather than guessing', () => {
    // Two deactivated accounts answer to one handle; an event naming it could
    // belong to either, and crediting both would invent an action.
    const { rows } = livingRoster(pieces, people, events);
    for (const p of rows.filter((r) => r.h === '(unresolvable)')) {
      expect(p.liveKinds).toBeNull();
    }
  });

  it('works with no event log at all', () => {
    const { rows } = livingRoster(pieces, people, null);
    for (const p of rows) expect(p.liveKinds).toBeNull();
  });
});

describe('hiddenReplies', () => {
  const events = {
    [SEED_PIECES[0].rkey]: [
      { k: 'reply', h: 'a.test', off: 10, pre: 1 },
      { k: 'reply', h: 'b.test', off: 80, pre: 0 },
      { k: 'like', h: 'c.test', off: 90, pre: 0 },
      { k: 'reply', h: 'dame.is', off: 70, pre: 0, self: 1 },
    ],
  };

  it('returns only non-self replies from after the seal', () => {
    const out = hiddenReplies(events, [SEED_PIECES[0]]);
    expect(out).toHaveLength(1);
    expect(out[0].h).toBe('b.test');
  });

  it('measures the offset from the seal, not from the post', () => {
    const [row] = hiddenReplies(events, [SEED_PIECES[0]]);
    // take #1 sealed at 48.832s; a reply at +80s landed ~31s after.
    expect(Math.round(row.afterSec)).toBe(31);
  });

  it('is empty until the event log has loaded', () => {
    expect(hiddenReplies(null, SEED_PIECES)).toEqual([]);
  });
});

describe('localSlot', () => {
  it('resolves into the artist’s zone, not UTC', () => {
    // 01:08 UTC on a Saturday is Friday evening in New York. Reading this in
    // UTC would put the piece on the wrong day AND the wrong half of the clock.
    const slot = localSlot('2026-02-21T01:08:01.648Z');
    expect(WEEKDAYS[slot.day]).toBe('Fri');
    expect(slot.hour).toBe(20);
    expect(slot.minute).toBe(8);
  });

  it('follows daylight saving rather than a fixed offset', () => {
    // June is EDT (UTC-4); February is EST (UTC-5). Same UTC hour, different
    // local hour.
    expect(localSlot('2025-06-16T18:13:22.654Z').hour).toBe(14);
    expect(localSlot('2026-02-21T18:13:22.000Z').hour).toBe(13);
  });

  it('gives a fractional hour for positioning', () => {
    expect(localSlot('2025-06-16T14:23:12.764Z').atHour).toBeCloseTo(10 + 23 / 60, 5);
  });

  it('returns null for an unparseable timestamp', () => {
    expect(localSlot('not a date')).toBeNull();
    expect(localSlot('')).toBeNull();
  });
});

describe('whenMarks', () => {
  const marks = whenMarks(SEED_PIECES);

  it('places every piece', () => {
    expect(marks).toHaveLength(SEED_PIECES.length);
    for (const m of marks) {
      expect(m.day).toBeGreaterThanOrEqual(0);
      expect(m.day).toBeLessThanOrEqual(6);
      expect(m.atHour).toBeGreaterThanOrEqual(0);
      expect(m.atHour).toBeLessThan(24);
    }
  });

  it('sums engagement across every kind that arrived while alive', () => {
    const four = marks.find((m) => m.take === 4);
    // 45 thread + 8 RT + 3 QT + 0 likes.
    expect(four.engagement).toBe(56);
    expect(four.participants).toBe(32);
  });

  it('lands the first three takes together on a Monday morning', () => {
    const early = marks.filter((m) => m.take <= 3);
    expect(early.every((m) => WEEKDAYS[m.day] === 'Mon')).toBe(true);
    expect(early.every((m) => m.hour === 10)).toBe(true);
  });

  it('drops a piece whose timestamp will not parse', () => {
    expect(whenMarks([{ ...SEED_PIECES[0], postedAt: 'nope' }])).toEqual([]);
  });
});

describe('areaRadius', () => {
  it('scales by area, so four times the value is twice the radius', () => {
    // Radius above the floor is what carries the value; check that span.
    const quarter = areaRadius(25, 100, 0, 10);
    const full = areaRadius(100, 100, 0, 10);
    expect(quarter).toBeCloseTo(5, 5);
    expect(full).toBeCloseTo(10, 5);
  });

  it('gives zero and empty maxima the floor rather than NaN', () => {
    expect(areaRadius(0, 100, 2, 10)).toBe(2);
    expect(areaRadius(5, 0, 2, 10)).toBe(2);
  });
});

describe('formatters', () => {
  it('formats durations under a minute as bare seconds', () => {
    expect(fmtDuration(48_832)).toBe('49s');
    expect(fmtDuration(0)).toBe('0s');
  });

  it('pads the seconds in minute-scale durations', () => {
    expect(fmtDuration(1_763_889)).toBe('29m24s');
    expect(fmtDuration(68_197)).toBe('1m08s');
  });

  it('keeps one decimal on reaction times and marks unknowns', () => {
    expect(fmtSeconds(11_304)).toBe('11.3s');
    expect(fmtSeconds(undefined)).toBe('—');
  });

  it('keeps two on a stopwatch, because that one is read while it moves', () => {
    expect(fmtStopwatch(4_283)).toBe('4.28s');
    expect(fmtStopwatch(0)).toBe('0.00s');
    // Minutes only when they exist, and the seconds stay padded so the number
    // doesn't change width as it ticks.
    expect(fmtStopwatch(67_420)).toBe('1m07.42s');
    expect(fmtStopwatch(600_000)).toBe('10m00.00s');
  });

  it('never runs a stopwatch backwards past zero', () => {
    // Local clock against a PDS write clock: the two can disagree by enough to
    // make "now" land before the like did.
    expect(fmtStopwatch(-250)).toBe('0.00s');
    expect(fmtStopwatch(null)).toBe('0.00s');
  });

  it('floats the unit across the afterlife range', () => {
    expect(fmtElapsed(31)).toBe('31s');
    expect(fmtElapsed(600)).toBe('10m');
    expect(fmtElapsed(7200)).toBe('2.0h');
    expect(fmtElapsed(86_400 * 405)).toBe('405d');
  });
});

describe('addressing a piece', () => {
  const pieces = [
    { rkey: '3lrq5r2ouw22b', take: 1 },
    { rkey: '3msyb4kntps2e', take: 13 },
  ];

  it('canonicalises a take to the padded form the UI shows', () => {
    expect(pieceSlug(pieces[0])).toBe('01');
    expect(pieceSlug(pieces[1])).toBe('13');
    expect(piecePath(pieces[1])).toBe('/creating/ratioed/13');
  });

  it('resolves a take number however it is written', () => {
    for (const ref of ['13', '013', '#13']) {
      expect(findPieceByRef(pieces, ref)?.take).toBe(13);
    }
    // A padded and a bare take must land on the same piece, or the two forms
    // become two URLs for one thing.
    expect(findPieceByRef(pieces, '01')).toBe(findPieceByRef(pieces, '1'));
  });

  it('resolves the record key, which is all a Bluesky link gives you', () => {
    expect(findPieceByRef(pieces, '3msyb4kntps2e')?.take).toBe(13);
  });

  it('refuses anything that names no piece', () => {
    expect(findPieceByRef(pieces, '99')).toBeNull();
    expect(findPieceByRef(pieces, 'ratioed')).toBeNull();
    expect(findPieceByRef(pieces, '')).toBeNull();
    expect(findPieceByRef(null, '13')).toBeNull();
  });

  it('answers under either address the parent document has', () => {
    // The essay is reachable at its human path AND its record key, so a piece
    // hanging off it has to be too.
    expect(isRatioedParent('ratioed', { rkey: '3mrlnl6oyuj2d' })).toBe(true);
    expect(isRatioedParent('3mrlnl6oyuj2d', { rkey: '3mrlnl6oyuj2d' })).toBe(true);
    expect(isRatioedParent('rainbow', { rkey: '3mrlnl6oyuj2d' })).toBe(false);
    expect(isRatioedParent('', { rkey: '3mrlnl6oyuj2d' })).toBe(false);
  });
});

describe('composeEventLog', () => {
  // The harvest's shape: seconds, a handle, and the text of every reply.
  const bundle = [
    { k: 'like', h: 'round.is', off: 31.8, pre: 1 },
    { k: 'quote', h: 'dawnkelly.bsky.social', off: 210, pre: 0, t: 'Is this why we cant have nice things?' },
  ];
  // A record repaired after the fact: the afterlife only, and no text, because
  // a backlink index does not carry any.
  const record = [
    { k: 'quote', h: 'dawnkelly.bsky.social', off: 209.993, pre: 0, did: 'did:plc:her', fr: 532 },
    { k: 'reply', h: 'later.test', off: 1391.2, pre: 0, did: 'did:plc:them', fr: 12 },
  ];

  it('keeps the harvested alive window a repaired record does not cover', () => {
    const out = composeEventLog(record, bundle);
    expect(out.filter((e) => e.pre)).toHaveLength(1);
    expect(out[0]).toMatchObject({ k: 'like', h: 'round.is', off: 31.8 });
  });

  it('gives a recorded row the text the harvest kept for it', () => {
    // Same kind, same account, within a second: the same record, measured
    // twice. The reply text is the one thing the index cannot give back.
    const out = composeEventLog(record, bundle);
    const quote = out.find((e) => e.k === 'quote');
    expect(quote.t).toBe('Is this why we cant have nice things?');
    expect(quote.fr).toBe(532); // and keeps what the record measured
  });

  it('does not list the same record twice', () => {
    const out = composeEventLog(record, bundle);
    expect(out.filter((e) => e.k === 'quote')).toHaveLength(1);
  });

  it('keeps a harvested row no index reports any more', () => {
    // A reply deleted since the harvest is absent from the record's fresh read
    // and present in the only measurement that ever saw it.
    const withGone = [...bundle, { k: 'reply', h: 'gone.test', off: 500, pre: 0, t: 'deleted since' }];
    const out = composeEventLog(record, withGone);
    expect(out.find((e) => e.h === 'gone.test')?.t).toBe('deleted since');
  });

  it('falls back to either source alone', () => {
    expect(composeEventLog(null, bundle)).toBe(bundle);
    expect(composeEventLog(record, null)).toBe(record);
    expect(composeEventLog(null, null)).toBeNull();
  });
});

describe('chaseTicks', () => {
  const record = { rkey: 'r14', take: 14, lifespanMs: 2_529_000 };
  const pieces = [
    { rkey: 'r01', take: 1, lifespanMs: 49_000 },
    { rkey: 'r14', take: 14, lifespanMs: 2_529_000 },
    { rkey: 'r16', take: 16, lifespanMs: 907_470 },
    { rkey: 'r15', take: 15, lifespanMs: 77_099 },
    { rkey: 'live', take: 17, lifespanMs: 0 }, // still up: no lifespan yet
  ];

  it('places one tick per finished piece, shortest first', () => {
    const ticks = chaseTicks(pieces, record, 0);
    expect(ticks.map((t) => t.take)).toEqual([1, 15, 16]);
    expect(ticks[0].at).toBeCloseTo(49_000 / 2_529_000);
  });

  it('leaves out the record itself — the bar already ends there', () => {
    expect(chaseTicks(pieces, record, 0).some((t) => t.rkey === 'r14')).toBe(false);
  });

  it('marks the ones the live piece has already outlived', () => {
    const ticks = chaseTicks(pieces, record, 100_000);
    expect(ticks.filter((t) => t.passed).map((t) => t.take)).toEqual([1, 15]);
  });

  it('is empty when nothing has finished yet', () => {
    expect(chaseTicks([], record, 0)).toEqual([]);
    expect(chaseTicks(pieces, null, 0)).toEqual([]);
  });
});

describe('foldFaces', () => {
  // Take 17's shape: the breaker replied twice on her way to the like, and the
  // like is what the face is for.
  const events = [
    { h: 'skye', did: 'did:a', k: 'reply', off: 2397.985, pre: 1 },
    { h: 'wolscott', did: 'did:b', k: 'reply', off: 2399.101, pre: 1 },
    { h: 'skye', did: 'did:a', k: 'reply', off: 2496.652, pre: 1 },
    { h: 'skye', did: 'did:a', k: 'like', off: 2503.064, pre: 1 },
    { h: 'dame', did: 'did:me', k: 'reply', off: 2531.871, pre: 0, self: 1 },
    { h: 'later', did: 'did:c', k: 'repost', off: 2518.605, pre: 0 },
  ];

  it('times a face by the act it is labelled for, not by its first', () => {
    const [wol, skye] = foldFaces(events).filter((p) => p.pre);
    expect(skye.handle).toBe('skye');
    expect(skye.kind).toBe('like');
    // Not 2397.985, which is when she first replied.
    expect(skye.off).toBeCloseTo(2503.064);
    // ...so the person who replied a second after her first reply comes first.
    expect(wol.handle).toBe('wolscott');
  });

  it('folds an account to one face and skips the artist', () => {
    const people = foldFaces(events);
    expect(people.map((p) => p.handle)).toEqual(['wolscott', 'skye', 'later']);
    expect(people.find((p) => p.handle === 'skye').count).toBe(3);
  });

  it('resolves each side of the seal on its own', () => {
    const [only] = foldFaces([
      { h: 'x', did: 'did:x', k: 'reply', off: 10, pre: 1 },
      { h: 'x', did: 'did:x', k: 'quote', off: 99, pre: 0 },
    ]);
    // Shown for being there while it was alive, which is the reply.
    expect(only.pre).toBe(true);
    expect(only.kind).toBe('reply');
    expect(only.off).toBe(10);
  });

  it('shows a repeated act at its first', () => {
    const [p] = foldFaces([
      { h: 'y', did: 'did:y', k: 'repost', off: 40, pre: 1 },
      { h: 'y', did: 'did:y', k: 'repost', off: 80, pre: 1 },
    ]);
    expect(p.off).toBe(40);
    expect(p.count).toBe(2);
  });

  it('keys on the handle when the log has no DID', () => {
    const [p] = foldFaces([{ h: 'z', k: 'reply', off: 3, pre: 1 }]);
    expect(p.key).toBe('h:z');
    expect(p.did).toBe(null);
  });

  it('is one face when the same person appears with and without a DID', () => {
    // A bundled take: the alive window is harvest, which carries no DIDs, and
    // the afterlife was written by a repair, which carries them. Two faces for
    // one account — and both ringed, since the breaker matches either way.
    const faces = foldFaces([
      { h: 'cam', k: 'reply', off: 967, pre: 1 },
      { h: 'cam', did: 'did:plc:cam', k: 'reply', off: 984, pre: 0 },
    ]);
    expect(faces).toHaveLength(1);
    expect(faces[0]).toMatchObject({ did: 'did:plc:cam', count: 2, pre: true });
  });

  it('will not merge two accounts that share the unresolvable placeholder', () => {
    const faces = foldFaces([
      { h: '(unresolvable)', k: 'reply', off: 1, pre: 1, rkey: 'a' },
      { h: '(unresolvable)', k: 'repost', off: 2, pre: 1, rkey: 'b' },
    ]);
    expect(faces).toHaveLength(2);
  });
});

describe('composeEventLog matches on identity, not only on the handle', () => {
  it('folds a re-resolved handle into the row it duplicates', () => {
    // Take 10's shape: the repair recorded the repost under a DID whose handle
    // would not resolve; the harvest has the same repost under the name the
    // account answered to at the time. 13ms apart, one record.
    const out = composeEventLog(
      [{ k: 'repost', h: '(unresolvable)', did: 'did:plc:rascal', off: 1163.713, pre: 0 }],
      [{ k: 'repost', h: 'rascalpyro.bsky.social', off: 1163.7, pre: 0, t: '' }],
    );
    expect(out).toHaveLength(1);
  });

  it('still keeps two different accounts apart at the same moment', () => {
    const out = composeEventLog(
      [{ k: 'repost', h: 'a.test', did: 'did:plc:a', off: 100, pre: 1 }],
      [{ k: 'repost', h: 'b.test', did: 'did:plc:b', off: 100.2, pre: 1 }],
    );
    expect(out).toHaveLength(2);
  });

  it('trusts two DIDs over two handles', () => {
    // Same handle, different accounts — a rename. Not one row.
    const out = composeEventLog(
      [{ k: 'reply', h: 'shared', did: 'did:plc:one', off: 10, pre: 1 }],
      [{ k: 'reply', h: 'shared', did: 'did:plc:two', off: 10.1, pre: 1 }],
    );
    expect(out).toHaveLength(2);
  });
});
