name: Generate RSS Feed
permissions:
  contents: write   # Allow write access to repository contents

on:
  push:
    branches: [ main ]
    paths:
      - 'blog/*.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Generate RSS Feed
        run: node generate-rss.js

      - name: Commit updated RSS feed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.xml
          if ! git diff --cached --quiet; then
            git commit -m "chore: update RSS feed [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
