name: Versioning

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Grants write access to repository contents, including tags

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          latest_tag=$(git tag -l 'v*.*.*' --sort=-v:refname | head -n 1)
          echo "Latest tag: $latest_tag"
          if [ -z "$latest_tag" ]; then
            new_tag="v1.0.0"
          else
            # Extract major, minor, patch
            major=$(echo $latest_tag | cut -d. -f1 | tr -d 'v')
            minor=$(echo $latest_tag | cut -d. -f2)
            patch=$(echo $latest_tag | cut -d. -f3)
            # Increment patch
            patch=$((patch + 1))
            new_tag="v$major.$minor.$patch"
          fi
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create New Tag
        id: create_tag
        run: |
          git tag ${{ steps.get_latest_tag.outputs.new_tag }}
          git push origin ${{ steps.get_latest_tag.outputs.new_tag }}

      - name: Output New Tag
        run: echo "New Tag: ${{ steps.get_latest_tag.outputs.new_tag }}"
